### ISSUE TITLE
How to address multiple multiplexer and shift register

### ISSUE THREAD

**Issue by mavoIn** [neroroxxx/RoxMux#2]
Hello,

your library looks very cool.

How can i use multiple shift register in chain and a multiplexer at the same time? 
How do i have to change your examples, in my case for example:

#define MUX_TOTAL_StellButtons 1
Rox74HC4067 <MUX_TOTAL_StellButtons> muxStellButtons;

#define MUX_TOTAL_StellLeds 3
Rox74HC165 <MUX_TOTAL_StellLeds> muxStellLeds;

thx

**Comment by neroroxxx** [comment]
Hi, yes you can use as many as you want and even have multiple chains of the same if you want.

Your code should work as is, just keep in mind that "Rox74HC165" is not for LEDs it's for digital inputs, it uses the 74HC165, for leds you want to use the Rox74HC595 example

**Comment by mavoIn** [comment]
Cool. thank you for your fast answer. sorry, i had a lot to do... no time for my hobby
