### ISSUE TITLE
No ability to use Wire1 TwoWire SDA1/SCL1

### ISSUE THREAD

**Issue by quiknick** [neroroxxx/RoxMux#9]
with other libraries such as MCP23017.h I can utilize Wire1 so that I can have some mux on SDA/SCL and some on SDA1/SCL1 Wire1 for specific reasons. I'd prefer to keep using RoxMux.h as I am using other modules of the library, but if I can't TwoWire working then I'll have to go back to another library.

In other libraries MCP23017 libraries I can do the following
`MCP23017 mux(0x20, &Wire1);`

In RoxMux.h and utilizing mux23017.h the only option is class address name
`RoxMCP23017 <0x20> mux;`

**Comment by neroroxxx** [comment]
I uploaded a quick change to give you the option in commit 99d10e5, I don't have a 23017 wired up at the moment but it should work, let me know if it works out and i'll update the library.

You'll have to initialize it this way

`RoxMCP2301X <0x20> mux(&Wire1);`

Note that you have to use  the `RoxMCP2301X` class not `RoxMCP23017`

**Comment by quiknick** [comment]
> I uploaded a quick change to give you the option in commit [99d10e5](https://github.com/neroroxxx/RoxMux/commit/99d10e5b686d49096e72d373809eb616871d3467), I don't have a 23017 wired up at the moment but it should work, let me know if it works out and i'll update the library.
> 
> You'll have to initialize it this way
> 
> `RoxMCP2301X <0x20> mux(&Wire1);`
> 
> Note that you have to use the `RoxMCP2301X` class not `RoxMCP23017`

Confirm this works. That was fast! Thank you!
